### ISSUE TITLE
What is the tensorflow version used?

### ISSUE THREAD

**Issue by DivyaRathod3D** [danilo-dessi/skg#1]
For me: tensorflow version 2.9.1 is giving me an error: AttributeError: module 'tensorflow' has no attribute 'Contrib'
and using version 1.14.1 is throwing: ImportError: cannot import name 'export_saved_model' from 'tensorflow.python.keras.saving.saved_model'

**Comment by danilo-dessi** [comment]
Note that tensorflow is used by the tool of Luan Yi et al. (https://bitbucket.org/luanyi/scierc/src/master/) and the suggested version is tensorflow 1.8.0 with python 2.7

**Comment by happycjksh** [comment]
I have used the tensorflow 1.8.0,but an  error will occur when I import the tensorflow-hub. The terminal said that cannot import name 'feature_column_v2' from tensorflow.python.feature_column. The reason is that the version of tensorflow-hub is match with tensorflow>2.3.0. However, the paper suggests the tensorflow version is 1.8.0. Could you please help me solve the problem?
